apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guest
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://1.2.3.4
      - cluster: prod
        url: https://2.4.6.8
      - cluster: preprod
        url: https://9.8.7.6
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      source:
        repoURL: https://github.com/infra-team/cluster-deployments.git
        targetRevision: HEAD
        path: guestbook/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: guestbook
